@file:Suppress("ktlint:standard:no-wildcard-imports", "WildcardImport")

package io.github.tulipltt.tulip.report

import kotlinx.html.*
import kotlinx.html.stream.appendHTML
import kotlinx.serialization.json.Json
import java.io.File

/**
 * Main generator for Tulip performance reports.
 */
object TulipReportGenerator {
    private val json =
        Json {
            ignoreUnknownKeys = true
            coerceInputValues = true
        }

    /**
     * Generates a complete HTML report from the provided [ReportData].
     */
    fun generateHtml(reportData: ReportData): String {
        val out = StringBuilder()
        out.append("<!DOCTYPE html>\n")
        out.appendHTML().html {
            lang = "en"
            attributes["data-theme"] = "dark"
            head {
                meta { charset = "UTF-8" }
                title { +"Tulip Performance Report" }
                link(
                    rel = "stylesheet",
                    href = "https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css",
                )
                style { unsafe { +ReportStyles.styles } }
                script { src = "https://cdn.jsdelivr.net/npm/echarts@5.5.0/dist/echarts.min.js" }
                script { unsafe { +ReportScripts.scripts } }
            }
            body {
                val groupedResults = reportData.results.groupBy { it.bmName }
                renderSidebar(groupedResults.keys)
                main {
                    renderMainHeader(reportData, groupedResults)
                    renderOverviewSection(groupedResults)
                    renderBenchmarkDetails(groupedResults)
                    renderConfigAndRuntime(reportData)
                    footer {
                        style = "text-align: center; padding: 2rem 0; opacity: 0.5;"
                        val msg = "Generated by Tulip Performance Tool • ${reportData.timestamp}"
                        p { +msg }
                    }
                }
            }
        }
        return out.toString()
    }

    private fun FlowContent.renderSidebar(benchmarkNames: Set<String>) {
        aside {
            id = "mySidebar"
            header {
                style = "display: flex; align-items: center; gap: 0.75rem; padding: 1.5rem;"
                unsafe { +ReportLogos.SMALL }
                h3 {
                    style = "margin: 0; font-size: 1.25rem;"
                    +"Tulip"
                }
            }
            nav {
                ul {
                    li { div(classes = "nav-section") { +"Overview" } }
                    renderNavLink("#overview", "Summary Dashboard", ReportIcons.DASHBOARD)
                    li { div(classes = "nav-section") { +"Benchmarks" } }
                    benchmarkNames.forEach { name ->
                        renderNavLink("#benchmark_${name.replace(" ", "_")}", name, ReportIcons.ACTIVITY)
                    }
                    li { div(classes = "nav-section") { +"Configuration" } }
                    renderNavLink("#config", "Benchmark Config", ReportIcons.SETTINGS)
                    renderNavLink("#runtime", "Tulip Runtime", ReportIcons.INFO)
                    li { div(classes = "nav-section") { +"Appearance" } }
                    li {
                        a(href = "javascript:void(0)", classes = "nav-link") {
                            attributes["onclick"] = "toggleTheme()"
                            unsafe { +ReportIcons.THEME }
                            +"Toggle Theme"
                        }
                    }
                }
            }
        }
    }

    private fun UL.renderNavLink(
        href: String,
        label: String,
        icon: String,
    ) {
        li {
            a(href = href, classes = "nav-link") {
                unsafe { +icon }
                +label
            }
        }
    }

    private fun FlowContent.renderMainHeader(
        reportData: ReportData,
        groupedResults: Map<String, List<BenchmarkResult>>,
    ) {
        header {
            div(classes = "grid") {
                div {
                    style = "display: flex; align-items: center; gap: 1rem;"
                    unsafe { +ReportLogos.LARGE }
                    div {
                        h2 {
                            style = "margin: 0;"
                            +"Performance Test Results"
                        }
                        small {
                            style = "opacity: 0.5;"
                            +"Tulip Performance Tool • Version ${reportData.version}"
                        }
                    }
                }
            }
            div(classes = "grid") {
                metricCard("Timestamp", reportData.timestamp)
                metricCard("Benchmarks", groupedResults.size.toString())
                val sumActions = reportData.results.sumOf { it.numActions.toLong() }.toString()
                metricCard("Total Actions", sumActions)
                metricCard("Total Failed", reportData.results.sumOf { it.numFailed.toLong() }.toString())
            }
        }
    }

    private fun FlowContent.renderOverviewSection(groupedResults: Map<String, List<BenchmarkResult>>) {
        div {
            id = "overview"
            statsCard("All Benchmarks Summary", classes = "full-width", tableId = "summary_table") {
                summaryTable(groupedResults, "summary_table")
            }
            renderCombinedCharts(groupedResults)
        }
    }

    private fun FlowContent.renderBenchmarkDetails(groupedResults: Map<String, List<BenchmarkResult>>) {
        groupedResults.forEach { (bmName, results) ->
            val bmId = bmName.replace(" ", "_")
            div {
                id = "benchmark_$bmId"
                h3 {
                    style = "margin-top: 2rem; border-bottom: 2px solid var(--pico-primary);"
                    +bmName
                }
                statsCard("Detailed Benchmark Results", classes = "full-width", tableId = "table_$bmId") {
                    detailedBenchmarkTable(results, "table_$bmId")
                }
                renderBenchmarkCharts(bmId, results)
            }
        }
    }

    private fun FlowContent.renderConfigAndRuntime(reportData: ReportData) {
        div {
            id = "config"
            h3 {
                style = "margin-top: 2rem; border-bottom: 2px solid var(--pico-primary);"
                +"Configuration"
            }
            configSection(reportData.config)
        }
        div {
            id = "runtime"
            h3 {
                style = "margin-top: 2rem; border-bottom: 2px solid var(--pico-primary);"
                +"Runtime Information"
            }
            runtimeSection(reportData)
        }
    }

    private fun FlowContent.metricCard(
        label: String,
        value: String,
    ) {
        article {
            style = "padding: 1rem; margin-bottom: 0;"
            small {
                style = "opacity: 0.5; display: block;"
                +label
            }
            strong {
                style = "font-size: 1.2rem;"
                +value
            }
        }
    }

    /**
     * Entry point for creating both HTML and AsciiDoc reports.
     */
    fun createReport(
        jsonPath: String,
        htmlOutputPath: String,
    ) {
        val jsonText = File(jsonPath).readText()
        val reportData = json.decodeFromString<ReportData>(jsonText)

        File(htmlOutputPath).writeText(generateHtml(reportData))

        val adocPath = htmlOutputPath.replace(".html", "_c.adoc")
        File(adocPath).writeText(ReportAdoc.generateAsciiDoc(reportData))

        ReportAdoc.convertAdocToHtml(adocPath)
    }
}

/**
 * SVG Logos for the Tulip brand.
 */
object ReportLogos {
    private val LOGO_SVG by lazy {
        ReportLogos::class.java.getResource("tulip_logo.svg")?.readText()
            ?: error("Resource tulip_logo.svg not found")
    }

    val SMALL by lazy { LOGO_SVG.replace("SIZE", "32") }
    val LARGE by lazy { LOGO_SVG.replace("SIZE", "64") }
}
